name: CI

on:
  push:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: macos-14  

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Show available Xcode versions
      run: ls -la /Applications/ | grep Xcode
    
    - name: Select Xcode 16.2
      run: sudo xcode-select -switch /Applications/Xcode_16.2.app || sudo xcode-select -switch /Applications/Xcode.app
    
    - name: Verify Xcode version
      run: xcodebuild -version
    
    - name: List available schemes
      run: xcodebuild -list -project EssentialFeed.xcodeproj
    
    - name: Build and Test
      run: |
        xcodebuild clean build test \
          -project EssentialFeed.xcodeproj \
          -scheme "CI" \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
